services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app # Sync the application code for development
      - ./data:/app/data # Mount the data directory as a volume
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    expose:
      - "80"
    volumes:
      - ./front:/app # Optional: For development, sync local files with the container
    stdin_open: true
    tty: true
    depends_on:
      - api
    networks:
      - elastic

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - api
    networks:
      - elastic

  elasticsearch:
    image: elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "discovery.seed_hosts=[]"
      - "action.destructive_requires_name=false"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local