general_parameters:
  city: Paris
  latitude: 48.85590544035335
  longitude: 2.325878356372592
  half_diagonal_coor: 0.03
  good_enough_Silhouette:
  good_enough_Calinski-Harabasz:
  good_enough_Davies-Bouldin:

plotting:
  enabled: true
  output_dir: "./data/plots"
  map_style: "carto-positron"  # Options: carto-positron, stamen-terrain, openstreetmap
  point_size: 5
  cluster_colors: ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf"]
  show_legend: true
  save_plots: true
  show_plots: false
  plot_format: "png"  # Options: png, jpg, pdf, svg
  dpi: 300

clustering_techniques:
  "Business center":
    method: optics
    params:
      min_samples: 5
      xi: 0.05
      max_eps: 0.4
      metric: euclidean
    
  "Cafe street":
    method: hdbscan
    params:
      min_cluster_size: 10
      min_samples: 5
      cluster_selection_epsilon: 0
      metric: haversine
    
  Museum:
    method: kmeans
    params:
      n_clusters: 5
      random_state: 42
    
  Park:
    method: kmeans
    params:
      n_clusters: 4
      random_state: 42
    
  Restaurant:
    method: hdbscan
    params:
      min_cluster_size: 8
      min_samples: 4
      cluster_selection_epsilon: 0
      metric: haversine
    
  University:
    method: optics
    params:
      min_samples: 7
      xi: 0.1
      metric: euclidean

  "Elite r.e.":
    method: hdbscan
    params:
      min_cluster_size: 8
      min_samples: 3
      cluster_selection_epsilon: 0.1
      metric: haversine
    
  "Upper r.e.":
    method: hdbscan
    params:
      min_cluster_size: 12
      min_samples: 4
      cluster_selection_epsilon: 0
      metric: haversine
    
  "Middle r.e.":
    method: hdbscan
    params:
      min_cluster_size: 15
      min_samples: 5
      cluster_selection_epsilon: 0.05
      metric: haversine
    
  "Lower r.e.":
    method: hdbscan
    params:
      min_cluster_size: 20
      min_samples: 6
      cluster_selection_epsilon: 0
      metric: haversine
    
  Cottage Settlement:
    method: kmeans
    params:
      n_clusters: 4
      random_state: 42
    
  Ethnic:
    method: spectral
    params:
      n_clusters: 6
      affinity: 'nearest_neighbors'
      n_neighbors: 10
    
  Nightlife:
    method: gmm
    params:
      n_components: 5
      covariance_type: 'full'
    
  Tourist:
    method: gmm
    params:
      n_components: 7
      covariance_type: 'tied'